cse-config-order: 100

## Spring Boot configurations
server:
  port: 8088

## CSE configurations
cse:
  rest:
    address: 0.0.0.0:8088
  handler:
    chain:
      Provider:
        default: tracing-provider
      Consumer:
        default: tracing-consumer,loadbalance